grafana:
  assertNoLeakedSecrets: false
  adminUser: admin
  adminPassword: admin

  grafana.ini:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false
    smtp:
      enabled: true
      host: smtp.gmail.com:587
      user: aboroni049@gmail.com
      password: 'easr mcvn ysnp kiqh'
      from_address: aboroni049@gmail.com
      from_name: CapBot Alerts
      skip_verify: false
    alerting:
      enabled: true
    unified_alerting:
      enabled: true

  persistence:
    enabled: true
    storageClassName: gp2  # You can run `kubectl get sc` to verify the correct one
    accessModes:
      - ReadWriteOnce
    size: 2Gi

  service:
    type: LoadBalancer

prometheus:
  enabled: true
  server:
    persistentVolume:
      enabled: false
    resources:
      limits:
        memory: 500Mi
        cpu: 500m
      requests:
        memory: 200Mi
        cpu: 100m
  additionalServiceMonitors:
    - name: kube-state-metrics
      selector:
        matchLabels:
          app.kubernetes.io/name: kube-state-metrics
      namespaceSelector:
        matchNames:
          - otel-helm
      endpoints:
        - port: http


