replicaCount: 1

adService:
  enabled: true

loadgenerator:
  enabled: true

otelCollector:
  config:
    exporters:
      logging:
        loglevel: debug

image:
  repository: 390844754612.dkr.ecr.us-east-1.amazonaws.com/otel-demo
  tag: frontend


